In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from preprocessing import dt_product_df, preprocess_text

In [7]:
### CONTENT BASED FILTERING ###
# Preprocessing kolom teks
text_colums_content = ['gender', 'skin_type_face', 'hair_issue', 'skin_type_body']

for column in text_colums_content:
    dt_product_df[column] = dt_product_df[column].apply(preprocess_text)

display(dt_product_df)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
0,4,2,10,Zinc Refreshing Cool - anti ketombe,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
1,4,2,10,Zinc Refreshing Cool - anti ketombe,4.0,perempuan,minyak,cabang,normal,123.0
2,4,2,10,Zinc Refreshing Cool - anti ketombe,5.0,lakilaki,normal,rontok,normal,212.0
3,4,2,10,Zinc Refreshing Cool - anti ketombe,5.0,perempuan,kombinasi,rontok,kering,174.0
4,4,2,10,Zinc Refreshing Cool - anti ketombe,5.0,perempuan,kering,cabang,normal,218.0
...,...,...,...,...,...,...,...,...,...,...
1778,316,3,18,Shinzui Glow Spa Honey,5.0,perempuan,minyak,ketombe,kombinasi,271.0
1779,316,3,18,Shinzui Glow Spa Honey,5.0,perempuan,kering,ketombe,kering,278.0
1780,316,3,18,Shinzui Glow Spa Honey,5.0,lakilaki,minyak,ketombe,normal,259.0
1781,316,3,18,Shinzui Glow Spa Honey,5.0,perempuan,normal,rontok,normal,178.0
1782,316,3,18,Shinzui Glow Spa Honey,5.0,lakilaki,normal,normal,kering,317.0

In [8]:
grouped_data = dt_product_df.groupby(['category_id', 'subcategory_id'])

for category_id, group in grouped_data:
    print(f"Category ID: {category_id}")
    display(group)
    print("\n")

Category ID: (1, 1)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
321,46,1,1,Face Tonic Lemon,5.0,lakilaki,normal,normal,normal,17.0
322,46,1,1,Face Tonic Lemon,5.0,perempuan,minyak,minyak,kombinasi,28.0
323,46,1,1,Face Tonic Lemon,5.0,perempuan,normal,ketombe,normal,40.0
324,46,1,1,Face Tonic Lemon,4.0,lakilaki,sensitif,normal,normal,48.0
325,46,1,1,Face Tonic Lemon,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
...,...,...,...,...,...,...,...,...,...,...
493,58,1,1,Micellar Water Salicylic BHA,5.0,perempuan,kombinasi,rontok,kering,168.0
494,58,1,1,Micellar Water Salicylic BHA,5.0,perempuan,kombinasi,minyak,normal,332.0
495,58,1,1,Micellar Water Salicylic BHA,5.0,perempuan,normal,rontok,normal,358.0
496,58,1,1,Micellar Water Salicylic BHA,4.0,perempuan,normal,normal,none,360.0
497,58,1,1,Micellar Water Salicylic BHA,5.0,lakilaki,minyak,kering,normal,363.0

Category ID: (1, 2)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
1216,171,1,2,Facial Wash bright white Gatsby,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
1217,171,1,2,Facial Wash bright white Gatsby,5.0,lakilaki,normal,normal,normal,133.0
1218,171,1,2,Facial Wash bright white Gatsby,5.0,lakilaki,minyak,normal,normal,136.0
1219,171,1,2,Facial Wash bright white Gatsby,5.0,perempuan,sensitif,normal,normal,215.0
1220,171,1,2,Facial Wash bright white Gatsby,5.0,perempuan,kering,cabang,normal,218.0
...,...,...,...,...,...,...,...,...,...,...
1444,255,1,2,Herborist Raspberry & tomato,5.0,perempuan,kering,minyak,normal,309.0
1445,256,1,2,Herborist facial wash tea tree,0.0,none,none,none,none,NaN
1446,257,1,2,herborist facial wash rose,0.0,none,none,none,none,NaN
1447,258,1,2,herborist facial wash zaitun,4.0,perempuan,sensitif,rontok,kering,64.0
1448,259,1,2,herborist facial wash aloe vera,3.0,lakilaki,normal,rontok,normal,52.0

Category ID: (1, 3)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
498,59,1,3,Wardah Acnederm Day Moisturizer,3.0,lakilaki,normal,normal,normal,17.0
499,59,1,3,Wardah Acnederm Day Moisturizer,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
500,59,1,3,Wardah Acnederm Day Moisturizer,5.0,lakilaki,sensitif,normal,normal,26.0
501,59,1,3,Wardah Acnederm Day Moisturizer,4.0,perempuan,kering,kering,kering,67.0
502,59,1,3,Wardah Acnederm Day Moisturizer,5.0,perempuan,normal,rontok,normal,89.0
503,59,1,3,Wardah Acnederm Day Moisturizer,5.0,perempuan,sensitif,minyak,normal,112.0
504,59,1,3,Wardah Acnederm Day Moisturizer,5.0,lakilaki,minyak,normal,normal,158.0
505,59,1,3,Wardah Acnederm Day Moisturizer,5.0,perempuan,sensitif,kering,kering,219.0
506,59,1,3,Wardah Acnederm Day Moisturizer,5.0,perempuan,kering,cabang,normal,218.0
507,59,1,3,Wardah Acnederm Day Moisturizer,5.0,perempuan,sensitif,normal,normal,275.0
508,59,1,3,Wardah Acnederm Day Moisturizer,5.0,perempuan,kombinasi,ketombe,kombinasi,299.0
509,59,1,3,Wardah Acnederm Day Moisturizer,5.0,perempuan,minyak,minyak,normal,240.0
510,59,1,3,Wardah Acnederm Day Moisturizer,5.0,perempuan,minyak,cabang,normal,330.0
511,60,1,3,Crystal Secret Day Cream,5.0,perempuan,kombinasi,ketombe,normal,41.0
512,60,1,3,Crystal Secret Day Cream,5.0,lakilaki,minyak,ketombe,kering,47.0
513,60,1,3,Crystal Secret Day Cream,4.0,perempuan,minyak,rontok,normal,57.0
514,60,1,3,Crystal Secret Day Cream,5.0,perempuan,minyak,cabang,minyak,60.0
515,60,1,3,Crystal Secret Day Cream,5.0,perempuan,kering,rontok,kering,120.0
516,60,1,3,Crystal Secret Day Cream,5.0,lakilaki,minyak,normal,normal,158.0
517,60,1,3,Crystal Secret Day Cream,5.0,perempuan,minyak,ketombe,kombinasi,271.0
518,60,1,3,Crystal Secret Day Cream,5.0,perempuan,kombinasi,ketombe,kombinasi,299.0
519,60,1,3,Crystal Secret Day Cream,5.0,perempuan,kombinasi,rontok,normal,312.0
520,60,1,3,Crystal Secret Day Cream,4.0,lakilaki,normal,kering,normal,314.0
521,60,1,3,Crystal Secret Day Cream,5.0,lakilaki,sensitif,normal,normal,26.0
522,60,1,3,Crystal Secret Day Cream,1.0,lakilaki,normal,normal,normal,331.0
523,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,normal,normal,normal,54.0
524,61,1,3,Hydra Rose Day Wardag,5.0,lakilaki,minyak,kering,normal,15.0
525,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,normal,rontok,normal,89.0
526,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,kombinasi,minyak,kering,99.0
527,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,kombinasi,rontok,kering,105.0
528,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,sensitif,minyak,normal,112.0
529,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,minyak,minyak,normal,154.0
530,61,1,3,Hydra Rose Day Wardag,5.0,lakilaki,minyak,normal,normal,158.0
531,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,minyak,kering,normal,162.0
532,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,kombinasi,rontok,kering,174.0
533,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,kering,ketombe,kering,220.0
534,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,minyak,ketombe,normal,235.0
535,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,normal,normal,normal,236.0
536,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,minyak,normal,normal,197.0
537,61,1,3,Hydra Rose Day Wardag,3.0,lakilaki,normal,normal,normal,276.0
538,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,minyak,normal,kering,258.0
539,61,1,3,Hydra Rose Day Wardag,5.0,lakilaki,normal,normal,kering,317.0
540,61,1,3,Hydra Rose Day Wardag,5.0,perempuan,normal,rontok,normal,358.0

Category ID: (1, 4)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
569,64,1,4,Night Treatment Moisturizer,5.0,perempuan,minyak,cabang,minyak,60.0
570,64,1,4,Night Treatment Moisturizer,3.0,perempuan,kering,kering,kering,67.0
571,64,1,4,Night Treatment Moisturizer,5.0,perempuan,normal,rontok,normal,89.0
572,64,1,4,Night Treatment Moisturizer,5.0,perempuan,kombinasi,ketombe,kombinasi,299.0
573,64,1,4,Night Treatment Moisturizer,5.0,lakilaki,sensitif,normal,normal,26.0
574,64,1,4,Night Treatment Moisturizer,5.0,lakilaki,normal,normal,normal,253.0
575,64,1,4,Night Treatment Moisturizer,4.0,perempuan,sensitif,ketombe,kering,33.0
576,65,1,4,Night Glow Night moisturizer,4.0,perempuan,normal,normal,normal,54.0
577,65,1,4,Night Glow Night moisturizer,5.0,perempuan,normal,normal,normal,225.0
578,65,1,4,Night Glow Night moisturizer,5.0,perempuan,kombinasi,minyak,normal,261.0
579,65,1,4,Night Glow Night moisturizer,4.0,perempuan,sensitif,normal,normal,275.0
580,65,1,4,Night Glow Night moisturizer,5.0,perempuan,normal,rontok,normal,358.0
581,66,1,4,Crystal Secret Night Cream,5.0,perempuan,kombinasi,ketombe,normal,41.0
582,66,1,4,Crystal Secret Night Cream,5.0,perempuan,minyak,ketombe,normal,235.0
583,66,1,4,Crystal Secret Night Cream,4.0,perempuan,kering,kering,kombinasi,273.0
584,67,1,4,Hydra Rose Night gel,5.0,perempuan,minyak,rontok,normal,57.0
585,67,1,4,Hydra Rose Night gel,5.0,perempuan,normal,normal,normal,236.0
586,67,1,4,Hydra Rose Night gel,4.0,perempuan,kering,kering,kombinasi,273.0
587,67,1,4,Hydra Rose Night gel,5.0,perempuan,kering,ketombe,kering,278.0
588,67,1,4,Hydra Rose Night gel,5.0,perempuan,minyak,ketombe,kombinasi,271.0
589,67,1,4,Hydra Rose Night gel,5.0,perempuan,minyak,normal,kering,258.0
590,67,1,4,Hydra Rose Night gel,5.0,lakilaki,minyak,normal,normal,310.0
591,67,1,4,Hydra Rose Night gel,5.0,perempuan,minyak,minyak,normal,240.0
592,68,1,4,Renew You,4.0,perempuan,normal,minyak,normal,7.0
593,68,1,4,Renew You,4.0,perempuan,normal,minyak,normal,7.0
594,68,1,4,Renew You,4.0,perempuan,normal,minyak,normal,7.0
595,68,1,4,Renew You,4.0,lakilaki,minyak,ketombe,kering,47.0
596,68,1,4,Renew You,5.0,lakilaki,minyak,kering,normal,15.0
597,68,1,4,Renew You,5.0,perempuan,kombinasi,kering,kering,65.0
598,68,1,4,Renew You,5.0,lakilaki,sensitif,normal,normal,26.0
599,68,1,4,Renew You,5.0,perempuan,kering,rontok,kering,120.0
600,68,1,4,Renew You,5.0,perempuan,sensitif,normal,kering,223.0
601,68,1,4,Renew You,5.0,lakilaki,normal,normal,kering,317.0
602,68,1,4,Renew You,2.0,lakilaki,normal,normal,normal,331.0

Category ID: (1, 5)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
603,69,1,5,Pixy Pollutional Off,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
604,69,1,5,Pixy Pollutional Off,4.0,lakilaki,minyak,minyak,minyak,125.0
605,69,1,5,Pixy Pollutional Off,5.0,perempuan,minyak,rontok,normal,130.0
606,69,1,5,Pixy Pollutional Off,5.0,perempuan,minyak,rontok,normal,130.0
607,69,1,5,Pixy Pollutional Off,5.0,perempuan,kombinasi,rontok,kering,174.0
...,...,...,...,...,...,...,...,...,...,...
669,78,1,5,Skintific Barrie Moisturizer Gel,5.0,perempuan,minyak,normal,kering,258.0
670,78,1,5,Skintific Barrie Moisturizer Gel,5.0,perempuan,kombinasi,rontok,normal,312.0
671,78,1,5,Skintific Barrie Moisturizer Gel,5.0,lakilaki,normal,normal,kering,317.0
672,78,1,5,Skintific Barrie Moisturizer Gel,5.0,perempuan,kombinasi,minyak,normal,332.0
673,78,1,5,Skintific Barrie Moisturizer Gel,5.0,perempuan,kombinasi,cabang,normal,357.0

Category ID: (1, 7)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
674,79,1,7,Nuface Cover me sun shield (SPF 30),5.0,perempuan,sensitif,ketombe,kombinasi,32.0
675,79,1,7,Nuface Cover me sun shield (SPF 30),4.0,lakilaki,normal,normal,normal,63.0
676,79,1,7,Nuface Cover me sun shield (SPF 30),5.0,perempuan,normal,kering,normal,149.0
677,79,1,7,Nuface Cover me sun shield (SPF 30),5.0,perempuan,kering,cabang,normal,218.0
678,79,1,7,Nuface Cover me sun shield (SPF 30),5.0,perempuan,minyak,rontok,normal,297.0
...,...,...,...,...,...,...,...,...,...,...
805,85,1,7,Emina Sun Battle (SPF 30),2.0,lakilaki,minyak,kering,normal,144.0
806,85,1,7,Emina Sun Battle (SPF 30),3.0,perempuan,kering,rontok,normal,213.0
807,85,1,7,Emina Sun Battle (SPF 30),5.0,perempuan,sensitif,kering,kering,219.0
808,85,1,7,Emina Sun Battle (SPF 30),5.0,perempuan,normal,rontok,normal,231.0
809,86,1,7,Pigeon (SPF 35),5.0,perempuan,minyak,kering,kering,109.0

Category ID: (1, 8)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
810,87,1,8,Acne Serum Scarlett,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
811,87,1,8,Acne Serum Scarlett,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
812,87,1,8,Acne Serum Scarlett,3.0,lakilaki,normal,rontok,normal,52.0
813,87,1,8,Acne Serum Scarlett,5.0,perempuan,normal,rontok,normal,89.0
814,87,1,8,Acne Serum Scarlett,5.0,perempuan,sensitif,minyak,normal,112.0
...,...,...,...,...,...,...,...,...,...,...
898,112,1,8,Luminous Brightening Serum Implora,5.0,perempuan,minyak,kering,kering,95.0
899,112,1,8,Luminous Brightening Serum Implora,4.0,perempuan,minyak,rontok,normal,94.0
900,112,1,8,Luminous Brightening Serum Implora,5.0,perempuan,minyak,rontok,normal,195.0
901,112,1,8,Luminous Brightening Serum Implora,5.0,perempuan,normal,rontok,normal,242.0
902,113,1,8,Hydra Glow Natural Hydrating Active AHA & Niac...,0.0,none,none,none,none,NaN

Category ID: (1, 9)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
541,62,1,9,Wardah Sleeping Mask C-defense,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
542,62,1,9,Wardah Sleeping Mask C-defense,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
543,62,1,9,Wardah Sleeping Mask C-defense,5.0,lakilaki,minyak,kering,normal,15.0
544,62,1,9,Wardah Sleeping Mask C-defense,5.0,perempuan,kombinasi,kering,kering,65.0
545,62,1,9,Wardah Sleeping Mask C-defense,5.0,lakilaki,sensitif,normal,normal,26.0
546,62,1,9,Wardah Sleeping Mask C-defense,3.0,perempuan,kering,kering,kering,67.0
547,62,1,9,Wardah Sleeping Mask C-defense,5.0,perempuan,normal,rontok,normal,92.0
548,62,1,9,Wardah Sleeping Mask C-defense,5.0,perempuan,kombinasi,minyak,kering,99.0
549,62,1,9,Wardah Sleeping Mask C-defense,5.0,perempuan,kering,rontok,kering,120.0
550,62,1,9,Wardah Sleeping Mask C-defense,5.0,lakilaki,minyak,normal,kering,217.0
551,62,1,9,Wardah Sleeping Mask C-defense,5.0,perempuan,kering,cabang,normal,218.0
552,62,1,9,Wardah Sleeping Mask C-defense,4.0,perempuan,sensitif,normal,normal,275.0
553,62,1,9,Wardah Sleeping Mask C-defense,5.0,perempuan,kombinasi,ketombe,kombinasi,299.0
554,62,1,9,Wardah Sleeping Mask C-defense,4.0,lakilaki,minyak,normal,normal,301.0
555,62,1,9,Wardah Sleeping Mask C-defense,5.0,lakilaki,minyak,normal,normal,310.0
556,62,1,9,Wardah Sleeping Mask C-defense,5.0,perempuan,minyak,minyak,normal,240.0
557,62,1,9,Wardah Sleeping Mask C-defense,5.0,perempuan,kombinasi,minyak,normal,332.0
558,63,1,9,Jelly Glow Sleeping Mask,3.0,perempuan,normal,minyak,normal,7.0
559,63,1,9,Jelly Glow Sleeping Mask,5.0,perempuan,minyak,rontok,normal,42.0
560,63,1,9,Jelly Glow Sleeping Mask,4.0,lakilaki,minyak,ketombe,kering,47.0
561,63,1,9,Jelly Glow Sleeping Mask,4.0,perempuan,normal,normal,normal,54.0
562,63,1,9,Jelly Glow Sleeping Mask,5.0,perempuan,normal,rontok,normal,89.0
563,63,1,9,Jelly Glow Sleeping Mask,5.0,lakilaki,normal,kering,normal,182.0
564,63,1,9,Jelly Glow Sleeping Mask,5.0,none,none,none,none,256.0
565,63,1,9,Jelly Glow Sleeping Mask,3.0,lakilaki,normal,normal,normal,331.0
566,63,1,9,Jelly Glow Sleeping Mask,4.0,lakilaki,normal,normal,normal,199.0
567,63,1,9,Jelly Glow Sleeping Mask,4.0,perempuan,normal,rontok,normal,358.0
568,63,1,9,Jelly Glow Sleeping Mask,4.0,perempuan,normal,rontok,normal,358.0

Category ID: (2, 10)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
0,4,2,10,Zinc Refreshing Cool - anti ketombe,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
1,4,2,10,Zinc Refreshing Cool - anti ketombe,4.0,perempuan,minyak,cabang,normal,123.0
2,4,2,10,Zinc Refreshing Cool - anti ketombe,5.0,lakilaki,normal,rontok,normal,212.0
3,4,2,10,Zinc Refreshing Cool - anti ketombe,5.0,perempuan,kombinasi,rontok,kering,174.0
4,4,2,10,Zinc Refreshing Cool - anti ketombe,5.0,perempuan,kering,cabang,normal,218.0
...,...,...,...,...,...,...,...,...,...,...
232,38,2,10,Dove Peraweatan Rambut Rontok (Hijau),5.0,perempuan,sensitif,minyak,normal,117.0
233,38,2,10,Dove Peraweatan Rambut Rontok (Hijau),4.0,perempuan,minyak,rontok,normal,138.0
234,38,2,10,Dove Peraweatan Rambut Rontok (Hijau),5.0,perempuan,kombinasi,normal,normal,208.0
235,38,2,10,Dove Peraweatan Rambut Rontok (Hijau),5.0,perempuan,kombinasi,rontok,normal,305.0
236,38,2,10,Dove Peraweatan Rambut Rontok (Hijau),5.0,perempuan,sensitif,rontok,kombinasi,191.0

Category ID: (2, 11)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
237,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
238,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,lakilaki,minyak,kering,normal,15.0
239,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,perempuan,kombinasi,kering,kering,65.0
240,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,lakilaki,normal,normal,normal,104.0
241,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,perempuan,kombinasi,rontok,kering,105.0
242,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,perempuan,minyak,kering,normal,164.0
243,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,perempuan,minyak,ketombe,kombinasi,271.0
244,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,perempuan,kering,kering,kombinasi,273.0
245,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,none,none,none,none,283.0
246,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,perempuan,sensitif,cabang,normal,289.0
247,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,lakilaki,kering,normal,normal,303.0
248,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,perempuan,kombinasi,rontok,normal,305.0
249,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,lakilaki,minyak,kering,kombinasi,316.0
250,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,5.0,perempuan,minyak,kering,normal,323.0
251,39,2,11,Putri Hair Tonic Ginseng - rambut rontok,4.0,perempuan,minyak,kering,normal,165.0
252,40,2,11,Putri Hair Tonic Hijau - rambut & Kulit normal...,4.0,perempuan,normal,normal,normal,54.0
253,40,2,11,Putri Hair Tonic Hijau - rambut & Kulit normal...,4.0,lakilaki,sensitif,normal,normal,26.0
254,40,2,11,Putri Hair Tonic Hijau - rambut & Kulit normal...,5.0,lakilaki,normal,normal,normal,104.0
255,40,2,11,Putri Hair Tonic Hijau - rambut & Kulit normal...,5.0,perempuan,minyak,kering,normal,164.0
256,40,2,11,Putri Hair Tonic Hijau - rambut & Kulit normal...,5.0,lakilaki,minyak,normal,kering,217.0
257,40,2,11,Putri Hair Tonic Hijau - rambut & Kulit normal...,5.0,lakilaki,minyak,ketombe,normal,233.0
258,40,2,11,Putri Hair Tonic Hijau - rambut & Kulit normal...,5.0,perempuan,kombinasi,minyak,normal,261.0
259,40,2,11,Putri Hair Tonic Hijau - rambut & Kulit normal...,2.0,lakilaki,normal,normal,normal,331.0
260,40,2,11,Putri Hair Tonic Hijau - rambut & Kulit normal...,5.0,perempuan,minyak,ketombe,normal,344.0
261,40,2,11,Putri Hair Tonic Hijau - rambut & Kulit normal...,5.0,perempuan,minyak,kering,normal,165.0
262,41,2,11,Putri Hair Tonic Kuning - rambut normal,5.0,lakilaki,normal,normal,normal,104.0
263,41,2,11,Putri Hair Tonic Kuning - rambut normal,5.0,lakilaki,minyak,ketombe,normal,259.0
264,41,2,11,Putri Hair Tonic Kuning - rambut normal,5.0,perempuan,minyak,kering,normal,323.0
265,41,2,11,Putri Hair Tonic Kuning - rambut normal,4.0,perempuan,minyak,kering,normal,165.0
266,41,2,11,Putri Hair Tonic Kuning - rambut normal,5.0,perempuan,normal,rontok,normal,358.0
267,42,2,11,Natur - Natural Extract - menebalkan rambut,4.0,none,none,none,none,12.0
268,42,2,11,Natur - Natural Extract - menebalkan rambut,3.0,perempuan,sensitif,kering,normal,23.0
269,42,2,11,Natur - Natural Extract - menebalkan rambut,2.0,perempuan,normal,minyak,normal,29.0
270,42,2,11,Natur - Natural Extract - menebalkan rambut,4.0,perempuan,kombinasi,ketombe,normal,41.0
271,42,2,11,Natur - Natural Extract - menebalkan rambut,4.0,perempuan,kombinasi,kering,kering,43.0
272,42,2,11,Natur - Natural Extract - menebalkan rambut,4.0,lakilaki,minyak,ketombe,kering,47.0
273,42,2,11,Natur - Natural Extract - menebalkan rambut,5.0,perempuan,minyak,rontok,normal,57.0
274,42,2,11,Natur - Natural Extract - menebalkan rambut,4.0,lakilaki,normal,rontok,kering,66.0
275,42,2,11,Natur - Natural Extract - menebalkan rambut,4.0,perempuan,kering,kering,kering,67.0
276,42,2,11,Natur - Natural Extract - menebalkan rambut,5.0,perempuan,normal,rontok,normal,89.0
277,42,2,11,Natur - Natural Extract - menebalkan rambut,5.0,perempuan,normal,normal,normal,101.0
278,42,2,11,Natur - Natural Extract - menebalkan rambut,5.0,lakilaki,normal,normal,normal,104.0
279,42,2,11,Natur - Natural Extract - menebalkan rambut,5.0,perempuan,kering,rontok,kering,120.0
280,42,2,11,Natur - Natural Extract - menebalkan rambut,5.0,perempuan,kombinasi,rontok,kering,129.0
281,42,2,11,Natur - Natural Extract - menebalkan rambut,5.0,perempuan,minyak,kering,normal,162.0
282,42,2,11,Natur - Natural Extract - menebalkan rambut,3.0,perempuan,minyak,kering,normal,164.0
283,42,2,11,Natur - Natural Extract - menebalkan rambut,5.0,perempuan,kombinasi,ketombe,kering,156.0
284,42,2,11,Natur - Natural Extract - menebalkan rambut,5.0,lakilaki,normal,kering,normal,182.0
285,42,2,11,Natur - Natural Extract - menebalkan rambut,5.0,perempuan,kombinasi,normal,normal,272.0
286,42,2,11,Natur - Natural Extract - menebalkan rambut,5.0,perempuan,kombinasi,rontok,kering,194.0
287,42,2,11,Natur - Natural Extract - menebalkan rambut,5.0,lakilaki,normal,kering,normal,314.0
288,42,2,11,Natur - Natural Extract - menebalkan rambut,5.0,lakilaki,normal,normal,normal,199.0
289,42,2,11,Natur - Natural Extract - menebalkan rambut,4.0,perempuan,minyak,kering,normal,165.0

Category ID: (2, 12)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
290,43,2,12,Wardah nutri shine - argan oil grape seed,4.0,none,none,none,none,12.0
291,43,2,12,Wardah nutri shine - argan oil grape seed,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
292,43,2,12,Wardah nutri shine - argan oil grape seed,5.0,lakilaki,minyak,kering,normal,15.0
293,43,2,12,Wardah nutri shine - argan oil grape seed,5.0,perempuan,kombinasi,kering,kering,65.0
294,43,2,12,Wardah nutri shine - argan oil grape seed,4.0,lakilaki,sensitif,normal,normal,26.0
295,43,2,12,Wardah nutri shine - argan oil grape seed,3.0,lakilaki,normal,normal,normal,63.0
296,43,2,12,Wardah nutri shine - argan oil grape seed,5.0,perempuan,kombinasi,rontok,kering,174.0
297,43,2,12,Wardah nutri shine - argan oil grape seed,5.0,perempuan,kering,cabang,normal,218.0
298,43,2,12,Wardah nutri shine - argan oil grape seed,5.0,lakilaki,minyak,ketombe,normal,233.0
299,43,2,12,Wardah nutri shine - argan oil grape seed,5.0,none,none,none,none,283.0
300,43,2,12,Wardah nutri shine - argan oil grape seed,4.0,perempuan,normal,normal,normal,293.0
301,43,2,12,Wardah nutri shine - argan oil grape seed,5.0,perempuan,kombinasi,ketombe,kombinasi,299.0
302,43,2,12,Wardah nutri shine - argan oil grape seed,4.0,lakilaki,minyak,normal,normal,301.0
303,43,2,12,Wardah nutri shine - argan oil grape seed,5.0,perempuan,minyak,normal,kering,258.0
304,43,2,12,Wardah nutri shine - argan oil grape seed,5.0,perempuan,kombinasi,rontok,normal,312.0
305,43,2,12,Wardah nutri shine - argan oil grape seed,3.0,lakilaki,normal,kering,normal,314.0
306,43,2,12,Wardah nutri shine - argan oil grape seed,2.0,lakilaki,normal,normal,normal,331.0
307,43,2,12,Wardah nutri shine - argan oil grape seed,5.0,perempuan,minyak,cabang,normal,330.0
308,43,2,12,Wardah nutri shine - argan oil grape seed,4.0,lakilaki,normal,normal,normal,199.0
309,43,2,12,Wardah nutri shine - argan oil grape seed,5.0,lakilaki,minyak,kering,normal,350.0
310,44,2,12,Putri Pure Clean Conditioner - fresh floral fr...,4.0,lakilaki,minyak,ketombe,kering,47.0
311,44,2,12,Putri Pure Clean Conditioner - fresh floral fr...,5.0,perempuan,minyak,rontok,normal,57.0
312,44,2,12,Putri Pure Clean Conditioner - fresh floral fr...,3.0,perempuan,kering,kering,kering,67.0
313,44,2,12,Putri Pure Clean Conditioner - fresh floral fr...,5.0,perempuan,kering,rontok,kering,120.0
314,44,2,12,Putri Pure Clean Conditioner - fresh floral fr...,3.0,perempuan,kombinasi,ketombe,normal,124.0
315,44,2,12,Putri Pure Clean Conditioner - fresh floral fr...,4.0,lakilaki,normal,kering,normal,182.0
316,44,2,12,Putri Pure Clean Conditioner - fresh floral fr...,5.0,lakilaki,sensitif,normal,normal,26.0
317,45,2,12,Putri Pure Clean Conditioner - fresh apple fra...,5.0,perempuan,normal,normal,normal,54.0
318,45,2,12,Putri Pure Clean Conditioner - fresh apple fra...,5.0,perempuan,normal,rontok,normal,89.0
319,45,2,12,Putri Pure Clean Conditioner - fresh apple fra...,5.0,lakilaki,minyak,kering,kombinasi,316.0
320,45,2,12,Putri Pure Clean Conditioner - fresh apple fra...,5.0,perempuan,normal,rontok,normal,358.0

Category ID: (3, 16)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
903,114,3,16,Gatsby Durable Deo Shield,5.0,perempuan,sensitif,kering,normal,37.0
904,114,3,16,Gatsby Durable Deo Shield,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
905,114,3,16,Gatsby Durable Deo Shield,4.0,lakilaki,minyak,ketombe,normal,233.0
906,114,3,16,Gatsby Durable Deo Shield,5.0,none,none,none,none,283.0
907,114,3,16,Gatsby Durable Deo Shield,5.0,lakilaki,minyak,minyak,minyak,167.0
...,...,...,...,...,...,...,...,...,...,...
1150,161,3,16,Lifebuoy - Lemon Fresh,5.0,perempuan,kering,rontok,kering,120.0
1151,161,3,16,Lifebuoy - Lemon Fresh,5.0,perempuan,kombinasi,rontok,normal,305.0
1152,162,3,16,Lifebuoy - Cool Fresh,5.0,perempuan,kombinasi,minyak,normal,261.0
1153,162,3,16,Lifebuoy - Cool Fresh,4.0,lakilaki,minyak,normal,normal,301.0
1154,162,3,16,Lifebuoy - Cool Fresh,5.0,lakilaki,normal,ketombe,normal,351.0

Category ID: (3, 17)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
1520,274,3,17,Citra Sakura Glow UV,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
1521,274,3,17,Citra Sakura Glow UV,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
1522,274,3,17,Citra Sakura Glow UV,5.0,perempuan,minyak,ketombe,normal,118.0
1523,274,3,17,Citra Sakura Glow UV,5.0,perempuan,normal,normal,normal,225.0
1524,274,3,17,Citra Sakura Glow UV,4.0,perempuan,minyak,ketombe,kombinasi,271.0
...,...,...,...,...,...,...,...,...,...,...
1735,312,3,17,Lovely White UV Nourish & Bright - Bengkoang,5.0,perempuan,sensitif,ketombe,normal,196.0
1736,312,3,17,Lovely White UV Nourish & Bright - Bengkoang,4.0,perempuan,minyak,normal,normal,197.0
1737,313,3,17,Lovely White UV Glow & Bright - Red Pomegranate,5.0,perempuan,normal,kering,normal,55.0
1738,313,3,17,Lovely White UV Glow & Bright - Red Pomegranate,4.0,perempuan,sensitif,rontok,kering,64.0
1739,313,3,17,Lovely White UV Glow & Bright - Red Pomegranate,4.0,lakilaki,normal,rontok,normal,52.0

Category ID: (3, 18)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
1740,314,3,18,Shinzui Glow Spa Ichigo,5.0,lakilaki,normal,normal,normal,17.0
1741,314,3,18,Shinzui Glow Spa Ichigo,5.0,perempuan,minyak,rontok,normal,42.0
1742,314,3,18,Shinzui Glow Spa Ichigo,5.0,lakilaki,kombinasi,rontok,kombinasi,49.0
1743,314,3,18,Shinzui Glow Spa Ichigo,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
1744,314,3,18,Shinzui Glow Spa Ichigo,5.0,perempuan,normal,rontok,normal,89.0
1745,314,3,18,Shinzui Glow Spa Ichigo,5.0,lakilaki,normal,normal,normal,108.0
1746,314,3,18,Shinzui Glow Spa Ichigo,3.0,perempuan,kering,rontok,kering,120.0
1747,314,3,18,Shinzui Glow Spa Ichigo,5.0,perempuan,kombinasi,rontok,kering,174.0
1748,314,3,18,Shinzui Glow Spa Ichigo,5.0,lakilaki,minyak,ketombe,normal,233.0
1749,314,3,18,Shinzui Glow Spa Ichigo,5.0,lakilaki,minyak,ketombe,normal,233.0
1750,314,3,18,Shinzui Glow Spa Ichigo,5.0,perempuan,kering,ketombe,kering,278.0
1751,314,3,18,Shinzui Glow Spa Ichigo,5.0,perempuan,kombinasi,ketombe,kombinasi,299.0
1752,314,3,18,Shinzui Glow Spa Ichigo,5.0,perempuan,normal,rontok,normal,178.0
1753,314,3,18,Shinzui Glow Spa Ichigo,5.0,perempuan,kombinasi,rontok,normal,312.0
1754,314,3,18,Shinzui Glow Spa Ichigo,4.0,lakilaki,normal,kering,normal,314.0
1755,314,3,18,Shinzui Glow Spa Ichigo,5.0,perempuan,normal,rontok,normal,358.0
1756,315,3,18,Shinzui Glow Spa Cica,3.0,lakilaki,normal,ketombe,minyak,11.0
1757,315,3,18,Shinzui Glow Spa Cica,3.0,lakilaki,normal,ketombe,minyak,11.0
1758,315,3,18,Shinzui Glow Spa Cica,3.0,none,none,none,none,12.0
1759,315,3,18,Shinzui Glow Spa Cica,4.0,lakilaki,kombinasi,rontok,kombinasi,49.0
1760,315,3,18,Shinzui Glow Spa Cica,4.0,perempuan,minyak,rontok,normal,57.0
1761,315,3,18,Shinzui Glow Spa Cica,3.0,lakilaki,sensitif,normal,normal,26.0
1762,315,3,18,Shinzui Glow Spa Cica,4.0,perempuan,kering,kering,kering,67.0
1763,315,3,18,Shinzui Glow Spa Cica,4.0,perempuan,kombinasi,rontok,kering,129.0
1764,315,3,18,Shinzui Glow Spa Cica,5.0,perempuan,kombinasi,rontok,kering,174.0
1765,315,3,18,Shinzui Glow Spa Cica,5.0,perempuan,kering,ketombe,kering,278.0
1766,315,3,18,Shinzui Glow Spa Cica,5.0,perempuan,minyak,minyak,normal,240.0
1767,315,3,18,Shinzui Glow Spa Cica,1.0,lakilaki,normal,normal,normal,331.0
1768,316,3,18,Shinzui Glow Spa Honey,5.0,perempuan,minyak,ketombe,kering,20.0
1769,316,3,18,Shinzui Glow Spa Honey,5.0,perempuan,minyak,rontok,normal,42.0
1770,316,3,18,Shinzui Glow Spa Honey,5.0,lakilaki,kombinasi,rontok,kombinasi,49.0
1771,316,3,18,Shinzui Glow Spa Honey,5.0,lakilaki,minyak,ketombe,kering,47.0
1772,316,3,18,Shinzui Glow Spa Honey,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
1773,316,3,18,Shinzui Glow Spa Honey,4.0,lakilaki,minyak,kering,normal,15.0
1774,316,3,18,Shinzui Glow Spa Honey,5.0,perempuan,minyak,rontok,normal,58.0
1775,316,3,18,Shinzui Glow Spa Honey,5.0,perempuan,kombinasi,kering,kering,65.0
1776,316,3,18,Shinzui Glow Spa Honey,5.0,lakilaki,minyak,kering,normal,141.0
1777,316,3,18,Shinzui Glow Spa Honey,5.0,perempuan,kombinasi,ketombe,kering,156.0
1778,316,3,18,Shinzui Glow Spa Honey,5.0,perempuan,minyak,ketombe,kombinasi,271.0
1779,316,3,18,Shinzui Glow Spa Honey,5.0,perempuan,kering,ketombe,kering,278.0
1780,316,3,18,Shinzui Glow Spa Honey,5.0,lakilaki,minyak,ketombe,normal,259.0
1781,316,3,18,Shinzui Glow Spa Honey,5.0,perempuan,normal,rontok,normal,178.0
1782,316,3,18,Shinzui Glow Spa Honey,5.0,lakilaki,normal,normal,kering,317.0

Category ID: (3, 19)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
1155,163,3,19,Herborist Body Serum - Mixed Berries & Taro,5.0,perempuan,normal,minyak,normal,29.0
1156,163,3,19,Herborist Body Serum - Mixed Berries & Taro,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
1157,163,3,19,Herborist Body Serum - Mixed Berries & Taro,5.0,lakilaki,sensitif,normal,normal,26.0
1158,163,3,19,Herborist Body Serum - Mixed Berries & Taro,4.0,perempuan,kombinasi,kering,kering,113.0
1159,163,3,19,Herborist Body Serum - Mixed Berries & Taro,5.0,none,none,none,none,283.0
1160,163,3,19,Herborist Body Serum - Mixed Berries & Taro,4.0,perempuan,kering,minyak,normal,309.0
1161,163,3,19,Herborist Body Serum - Mixed Berries & Taro,5.0,perempuan,minyak,minyak,normal,240.0
1162,163,3,19,Herborist Body Serum - Mixed Berries & Taro,4.0,perempuan,normal,normal,normal,334.0
1163,163,3,19,Herborist Body Serum - Mixed Berries & Taro,5.0,perempuan,minyak,ketombe,normal,344.0
1164,163,3,19,Herborist Body Serum - Mixed Berries & Taro,5.0,perempuan,normal,rontok,normal,358.0
1165,164,3,19,Herborist Body Serum - Orange & Carrot,4.0,perempuan,kombinasi,ketombe,normal,41.0
1166,164,3,19,Herborist Body Serum - Orange & Carrot,4.0,perempuan,minyak,rontok,normal,57.0
1167,164,3,19,Herborist Body Serum - Orange & Carrot,5.0,perempuan,kering,rontok,kering,120.0
1168,164,3,19,Herborist Body Serum - Orange & Carrot,5.0,perempuan,minyak,rontok,normal,138.0
1169,164,3,19,Herborist Body Serum - Orange & Carrot,3.0,perempuan,minyak,kering,normal,162.0
1170,164,3,19,Herborist Body Serum - Orange & Carrot,5.0,perempuan,kombinasi,rontok,normal,305.0
1171,164,3,19,Herborist Body Serum - Orange & Carrot,5.0,perempuan,minyak,normal,normal,96.0
1172,165,3,19,Herborist Body Serum - Apple & Broccoli,5.0,perempuan,kombinasi,ketombe,normal,41.0
1173,165,3,19,Herborist Body Serum - Apple & Broccoli,5.0,perempuan,normal,normal,normal,54.0
1174,165,3,19,Herborist Body Serum - Apple & Broccoli,5.0,lakilaki,minyak,kering,normal,15.0
1175,165,3,19,Herborist Body Serum - Apple & Broccoli,5.0,perempuan,normal,rontok,normal,89.0
1176,165,3,19,Herborist Body Serum - Apple & Broccoli,5.0,perempuan,minyak,normal,normal,96.0
1177,165,3,19,Herborist Body Serum - Apple & Broccoli,5.0,perempuan,kering,rontok,kering,120.0
1178,165,3,19,Herborist Body Serum - Apple & Broccoli,4.0,perempuan,minyak,rontok,normal,138.0
1179,165,3,19,Herborist Body Serum - Apple & Broccoli,5.0,perempuan,minyak,minyak,normal,154.0
1180,165,3,19,Herborist Body Serum - Apple & Broccoli,5.0,lakilaki,minyak,ketombe,normal,233.0
1181,165,3,19,Herborist Body Serum - Apple & Broccoli,4.0,perempuan,normal,rontok,normal,166.0
1182,166,3,19,Vaseline Super Food Cranberry Bright Glow Skin,1.0,perempuan,kombinasi,rontok,normal,21.0
1183,166,3,19,Vaseline Super Food Cranberry Bright Glow Skin,5.0,lakilaki,normal,rontok,kering,66.0
1184,166,3,19,Vaseline Super Food Cranberry Bright Glow Skin,4.0,perempuan,kering,kering,kering,67.0
1185,166,3,19,Vaseline Super Food Cranberry Bright Glow Skin,5.0,perempuan,minyak,rontok,normal,138.0
1186,166,3,19,Vaseline Super Food Cranberry Bright Glow Skin,5.0,perempuan,minyak,rontok,normal,172.0
1187,166,3,19,Vaseline Super Food Cranberry Bright Glow Skin,4.0,lakilaki,normal,normal,kering,317.0
1188,166,3,19,Vaseline Super Food Cranberry Bright Glow Skin,4.0,lakilaki,normal,normal,kering,317.0
1189,166,3,19,Vaseline Super Food Cranberry Bright Glow Skin,5.0,perempuan,minyak,normal,normal,96.0
1190,167,3,19,Vaseline Body Yogurt with Prebiotics,4.0,lakilaki,normal,normal,normal,17.0
1191,167,3,19,Vaseline Body Yogurt with Prebiotics,4.0,none,none,none,none,12.0

Category ID: (3, 20)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
1192,168,3,20,Sariayu Olive Oil,4.0,none,none,none,none,12.0
1193,168,3,20,Sariayu Olive Oil,5.0,perempuan,minyak,rontok,normal,42.0
1194,168,3,20,Sariayu Olive Oil,5.0,lakilaki,minyak,ketombe,kering,47.0
1195,168,3,20,Sariayu Olive Oil,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
1196,168,3,20,Sariayu Olive Oil,4.0,perempuan,normal,normal,normal,54.0
1197,168,3,20,Sariayu Olive Oil,5.0,perempuan,minyak,rontok,normal,57.0
1198,168,3,20,Sariayu Olive Oil,5.0,perempuan,kering,kering,kering,67.0
1199,168,3,20,Sariayu Olive Oil,5.0,perempuan,normal,rontok,normal,89.0
1200,168,3,20,Sariayu Olive Oil,5.0,perempuan,normal,rontok,normal,92.0
1201,168,3,20,Sariayu Olive Oil,5.0,perempuan,kering,rontok,kering,120.0
1202,168,3,20,Sariayu Olive Oil,5.0,perempuan,minyak,rontok,normal,138.0
1203,168,3,20,Sariayu Olive Oil,5.0,perempuan,minyak,kering,normal,162.0
1204,168,3,20,Sariayu Olive Oil,5.0,perempuan,kombinasi,rontok,kering,174.0
1205,168,3,20,Sariayu Olive Oil,5.0,perempuan,minyak,rontok,normal,172.0
1206,168,3,20,Sariayu Olive Oil,5.0,lakilaki,minyak,normal,kering,217.0
1207,168,3,20,Sariayu Olive Oil,5.0,none,none,none,none,283.0
1208,168,3,20,Sariayu Olive Oil,5.0,perempuan,kombinasi,rontok,normal,305.0
1209,168,3,20,Sariayu Olive Oil,4.0,perempuan,normal,normal,normal,334.0
1210,168,3,20,Sariayu Olive Oil,5.0,perempuan,normal,rontok,normal,358.0
1211,169,3,20,Purbasari Olive Oil with Jasmine Essential Oil,4.0,lakilaki,minyak,kering,normal,15.0
1212,170,3,20,Herborist Olive Oil,5.0,perempuan,minyak,minyak,normal,59.0
1213,170,3,20,Herborist Olive Oil,3.0,lakilaki,sensitif,normal,normal,26.0
1214,170,3,20,Herborist Olive Oil,4.0,lakilaki,minyak,ketombe,normal,233.0
1215,170,3,20,Herborist Olive Oil,5.0,perempuan,kombinasi,normal,normal,285.0

Category ID: (3, 21)

,id,category_id,subcategory_id,name,rating,gender,skin_type_face,hair_issue,skin_type_body,user_id
1449,260,3,21,Herborist Lulur Tradisional Bali - Coconut,5.0,perempuan,sensitif,ketombe,kombinasi,32.0
1450,260,3,21,Herborist Lulur Tradisional Bali - Coconut,5.0,perempuan,minyak,kering,kering,95.0
1451,260,3,21,Herborist Lulur Tradisional Bali - Coconut,5.0,lakilaki,normal,normal,normal,104.0
1452,260,3,21,Herborist Lulur Tradisional Bali - Coconut,5.0,perempuan,normal,kering,normal,149.0
1453,260,3,21,Herborist Lulur Tradisional Bali - Coconut,5.0,perempuan,minyak,rontok,normal,138.0
...,...,...,...,...,...,...,...,...,...,...
1515,273,3,21,Purbasari Lulur Mandi Susu & Bengkoang,5.0,perempuan,kombinasi,normal,normal,285.0
1516,273,3,21,Purbasari Lulur Mandi Susu & Bengkoang,5.0,perempuan,kombinasi,rontok,normal,305.0
1517,273,3,21,Purbasari Lulur Mandi Susu & Bengkoang,5.0,perempuan,kering,minyak,normal,309.0
1518,273,3,21,Purbasari Lulur Mandi Susu & Bengkoang,5.0,perempuan,kombinasi,rontok,kering,168.0
1519,273,3,21,Purbasari Lulur Mandi Susu & Bengkoang,5.0,perempuan,kombinasi,minyak,normal,332.0

In [9]:
# Fungsi untuk menghitung TF-IDF dan similaritas kosinus serta memberikan rekomendasi
def calculate_similarity(group, user_id):
    # Inisialisasi TF-IDF Vectorizer
    tfidf_vectorizer = TfidfVectorizer()

    # Ambil atribut untuk perhitungan (skin_type)
    attributes = group[['skin_type_face', 'hair_issue', 'skin_type_body']].astype(str).apply(lambda x: ' '.join(x), axis=1)

    # Hitung TF-IDF
    tfidf_matrix = tfidf_vectorizer.fit_transform(attributes)

    # Ambil data produk yang sudah dirating oleh user
    rated_products = set(group[group['user_id'] == user_id]['id'])

    # Jika user belum melakukan rating, kembalikan array kosong
    if not rated_products:
        return []
    
    # Ambil jumlah total rating dan rata-rata rating
    total_ratings = group['rating'].sum()
    average_rating = group['rating'].mean()

    # Inisialisasi list untuk menyimpan rekomendasi produk
    recommendations = []

    # Ambil indeks produk yang dirating oleh user
    rated_indices = [idx for idx, product_id in enumerate(group['id']) if product_id in rated_products]

    # Lakukan iterasi melalui setiap produk yang dirating oleh user
    for query_index in rated_indices:
        # Ambil query dan lakukan reshape
        query = tfidf_matrix[query_index]

        # Hitung similaritas kosinus antara query dan semua produk
        cosine_similarities = cosine_similarity(query, tfidf_matrix).flatten()

        # Urutkan indeks produk berdasarkan similaritas kosinus
        similar_indices = cosine_similarities.argsort()[::-1]

        # Tambahkan produk, termasuk yang sudah dirating oleh user, ke dalam list recommendations
        for idx in similar_indices:
            # Hitung bobot rekomendasi berdasarkan nilai similaritas, bobot TF-IDF, jumlah rating, dan rata-rata rating
            recommendation_weight = (0.3 * tfidf_matrix[idx, :].sum() + 
                                     0.6 * cosine_similarities[idx] + 
                                     0.05 * (group.iloc[idx]['rating'] / total_ratings) + 
                                     0.05 * (group.iloc[idx]['rating'] / average_rating))
            recommendations.append((group.iloc[idx]['id'], recommendation_weight))
            if len(recommendations) >= 16:
                break

        if len(recommendations) >= 16: 
            break

    # Urutkan rekomendasi berdasarkan nilai similaritas tertinggi
    recommendations.sort(key=lambda x: x[1], reverse=True)

    # Mengambil hanya id produk dari rekomendasi
    recommended_product_ids = [rec[0] for rec in recommendations]

    # Mengembalikan rekomendasi
    return recommended_product_ids

In [10]:
# Looping melalui semua user untuk melihat hasil rekomendasi
user_ids = dt_product_df['user_id'].unique()

all_recommendations = {}

for user_id in user_ids:
    category_recommendations = {}
    for (category_id, subcategory_id), group in grouped_data:
        recommendations = calculate_similarity(group, user_id)
        if recommendations:
            category_key = f"Category {category_id}, Subcategory {subcategory_id}"
            category_recommendations[category_key] = recommendations
    
    all_recommendations[user_id] = category_recommendations

# Displaying recommendations for user 32 as an example
user_id_to_display = 32
if user_id_to_display in all_recommendations:
    print(f"User ID: {user_id_to_display}")
    for category, recommendations in all_recommendations[user_id_to_display].items():
        print(f"{category}: {recommendations}")
else:
    print(f"No recommendations for User ID: {user_id_to_display}")

User ID: 32
Category 1, Subcategory 1: [46, 52, 57, 50, 48, 46, 46, 58, 46, 57, 48, 47, 56, 56, 58, 51]
Category 1, Subcategory 2: [171, 215, 171, 211, 218, 211, 226, 246, 224, 219, 171, 176, 236, 215, 211, 215]
Category 1, Subcategory 3: [61, 59, 60, 61, 61, 61, 61, 60, 59, 61, 61, 59, 61, 60, 60, 59]
Category 1, Subcategory 5: [69, 69, 73, 78, 78, 72, 78, 69, 78, 78, 78, 77, 75, 78, 74, 71]
Category 1, Subcategory 7: [79, 82, 84, 82, 81, 82, 82, 83, 81, 84, 81, 82, 82, 79, 82, 84]
Category 1, Subcategory 8: [87, 87, 92, 94, 87, 95, 87, 90, 92, 91, 90, 89, 87, 87, 88, 95]
Category 1, Subcategory 9: [62, 62, 62, 63, 62, 62, 62, 62, 62, 62, 62, 62, 62, 63, 62, 62]
Category 2, Subcategory 10: [4, 19, 38, 33, 13, 37, 23, 24, 24, 25, 15, 23, 36, 24, 14, 4]
Category 2, Subcategory 11: [39, 42, 39, 42, 42, 40, 40, 41, 42, 40, 39, 40, 39, 39, 39, 42]
Category 2, Subcategory 12: [43, 43, 43, 43, 43, 43, 43, 43, 43, 45, 43, 43, 43, 43, 43, 43]
Category 3, Subcategory 16: [114, 161, 139, 149, 147, 135, 121, 135, 120, 114, 140, 120, 122, 141, 121, 140]
Category 3, Subcategory 17: [274, 274, 312, 305, 300, 299, 310, 309, 309, 285, 274, 285, 274, 299, 277, 294]
Category 3, Subcategory 18: [314, 314, 314, 316, 316, 314, 314, 314, 315, 316, 314, 316, 316, 315, 315, 316]
Category 3, Subcategory 19: [163, 166, 164, 165, 164, 166, 166, 165, 164, 163, 164, 165, 163, 165, 163, 167]
Category 3, Subcategory 20: [168, 168, 168, 168, 168, 168, 168, 168, 168, 170, 170, 168, 168, 168, 168, 168]
Category 3, Subcategory 21: [260, 267, 260, 267, 263, 260, 261, 273, 260, 260, 261, 261, 273, 261, 260, 265]