In [1]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from preprocessing import dt_profiles_rating_df, preprocess_text

C:\Users\jeffr\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ud-anthony.vpnstores.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\jeffr\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ud-anthony.vpnstores.net'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [2]:
### USER BASED FILLTERING ###
text_colums_user = ['gender','skin_type_face', 'hair_issue', 
                'skin_type_body', 'allergy_history', 'preferred_products', 
                'avoided_products', 'specific_needs']
                
for column in text_colums_user:
    dt_profiles_rating_df[column] = dt_profiles_rating_df[column].apply(preprocess_text)

In [3]:
# convert skin type, hair issue, skin type body to numeric value (int)
def convert_skin_type_face(skin_type): 
    skin_type_dict = {'normal': 0, 'kering': 1, 'minyak': 2, 'sensitif': 3, 'kombinasi': 4}
    return skin_type_dict.get(skin_type, 0)

def convert_hair_issue(hair_issue): 
    hair_issue_dict = {'normal': 0, 'ketombe': 1, 'kering': 2, 'minyak': 3, 'rontok': 4, 'cabang': 5}
    return hair_issue_dict.get(hair_issue, 0)

def convert_skin_type_body(skin_type): 
    skin_type_dict = {'normal': 0, 'kering': 1, 'minyak': 2, 'kombinasi': 3} 
    return skin_type_dict.get(skin_type, 0)

dt_profiles_rating_df["skin_type_face"] = dt_profiles_rating_df["skin_type_face"].apply(convert_skin_type_face) 
dt_profiles_rating_df["hair_issue"] = dt_profiles_rating_df["hair_issue"].apply(convert_hair_issue) 
dt_profiles_rating_df["skin_type_body"] = dt_profiles_rating_df["skin_type_body"].apply(convert_skin_type_body)

In [4]:
# Precompute user vectors
user_vectors = dt_profiles_rating_df.groupby('user_id')[['skin_type_face', 'hair_issue', 'skin_type_body']].mean().round(2)
user_vectors.reset_index(inplace=True)
display(user_vectors)

user_vectors = user_vectors[user_vectors['user_id'].isin(dt_profiles_rating_df['user_id'].unique())]
user_ids = user_vectors['user_id']
user_vectors = user_vectors.drop('user_id', axis=1)
user_similarities = cosine_similarity(user_vectors)
user_similarities = pd.DataFrame(user_similarities, index=user_ids, columns=user_ids).round(2)
display(user_similarities)

# Get unique items
items = dt_profiles_rating_df['product_id'].unique()
display(items)

     user_id  skin_type_face  hair_issue  skin_type_body
0          1             0.0         0.0             0.0
1          7             0.0         3.0             0.0
2          8             3.0         2.0             1.0
3         11             0.0         1.0             2.0
4         12             0.0         0.0             0.0
..       ...             ...         ...             ...
294      360             0.0         1.0             0.0
295      361             0.0         1.0             0.0
296      362             0.0         1.0             0.0
297      363             2.0         2.0             0.0
298      364             0.0         1.0             0.0

[299 rows x 4 columns]

user_id,1,7,8,11,12,13,14,15,16,17,...,355,356,357,358,359,360,361,362,363,364
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
7,0.0,1.00,0.53,0.45,0.0,0.45,0.45,0.71,1.00,1.00,...,1.00,0.24,0.78,1.00,1.00,1.00,1.00,1.00,0.71,1.00
8,0.0,0.53,1.00,0.48,0.0,0.96,0.96,0.94,0.53,0.53,...,0.53,0.91,0.92,0.53,0.53,0.53,0.53,0.53,0.94,0.53
11,0.0,0.45,0.48,1.00,0.0,0.20,0.20,0.32,0.45,0.45,...,0.45,0.11,0.35,0.45,0.45,0.45,0.45,0.45,0.32,0.45
12,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,0.0,1.00,0.53,0.45,0.0,0.45,0.45,0.71,1.00,1.00,...,1.00,0.24,0.78,1.00,1.00,1.00,1.00,1.00,0.71,1.00
361,0.0,1.00,0.53,0.45,0.0,0.45,0.45,0.71,1.00,1.00,...,1.00,0.24,0.78,1.00,1.00,1.00,1.00,1.00,0.71,1.00
362,0.0,1.00,0.53,0.45,0.0,0.45,0.45,0.71,1.00,1.00,...,1.00,0.24,0.78,1.00,1.00,1.00,1.00,1.00,0.71,1.00
363,0.0,0.71,0.94,0.32,0.0,0.95,0.95,1.00,0.71,0.71,...,0.71,0.86,0.99,0.71,0.71,0.71,0.71,0.71,1.00,0.71
364,0.0,1.00,0.53,0.45,0.0,0.45,0.45,0.71,1.00,1.00,...,1.00,0.24,0.78,1.00,1.00,1.00,1.00,1.00,0.71,1.00

array([  0, 215,  22, 311, 286,  82, 140, 112,  63,  51,  21,  18,   5,
         8,  68,  92,  85, 216, 307, 280, 276, 236,  58,  24, 300, 315,
         7, 294, 134,  42,  43, 123, 167, 168, 199,  84, 283,  16, 309,
        47,  20, 263,  35, 135, 219,  61,  78,  93,  62,  39, 282, 316,
       165, 169, 261, 191,   6, 295, 122, 314,  46, 312, 306,  59, 188,
        36, 138, 298,  81, 166, 310,  56,  23, 161, 207, 252,  40, 179,
        95, 141, 163, 170,  14, 177,  87, 120,  64,  77,  44,  26,  60,
       208,  94, 302, 228, 193, 147,  32,   4, 171,  69,  79, 114, 274,
       260, 160,   9, 304, 234, 218, 285, 299,  15,  37,  25,  83, 121,
       156, 159,  66, 164,  57, 211,  13, 305,  50, 116, 149,  33,  12,
       175, 130, 273, 217,  30, 313, 259, 137,  73, 232,  45,  65,  75,
        34, 187,  67, 265, 255,  28, 233, 214,  74,  96, 278, 267, 258,
       195, 229, 292, 254, 251, 227, 178, 139,  99,  98,  97,  88,  71,
        55, 146, 262, 212, 279,  49, 246, 173, 210, 124, 287,  41, 176,
        52,  86,  11, 190,  89,  90,  91, 266,  38, 277, 249, 220, 226,
       106, 102,  17, 128, 275, 209, 253, 250,  19, 148, 151, 153, 154,
       155, 281, 284, 264,  29, 301, 247, 119, 142,  48, 224, 225, 180,
        54, 181, 182, 174,  70, 172,  80, 183, 145,  31, 291, 115,  53,
       297, 296,  72, 125, 152, 162, 126, 129,  76, 197, 268, 108, 204,
       271, 117, 206, 202, 118, 201, 150])

In [5]:
# Function to get recommendations
def get_user_based_recommendations(user_id):
    predictions = {}
    similarity_sum = user_similarities.loc[user_id].sum()
    
    if similarity_sum > 0:
        for item in items:
            other_user_ratings = dt_profiles_rating_df[dt_profiles_rating_df['product_id'] == item]
            rating_sum = 0
            weight_sum = 0
            for other_user_id in other_user_ratings['user_id']:
                if other_user_id != user_id:
                    rating = other_user_ratings[other_user_ratings['user_id'] == other_user_id]['rating'].values[0]
                    similarity = user_similarities.loc[user_id, other_user_id]
                    rating_sum += rating * similarity
                    weight_sum += similarity
            if weight_sum > 0:
                predictions[item] = rating_sum / weight_sum
            
    recommendations = sorted(predictions, key=predictions.get, reverse=True)[:10]
    return recommendations

# Display recommendations for each user
unique_user_ids = dt_profiles_rating_df['user_id'].unique()

In [6]:
for user_id in unique_user_ids:
    recommendations = get_user_based_recommendations(user_id)
    user_name = dt_profiles_rating_df[dt_profiles_rating_df['user_id'] == user_id]['user_name'].values[0]  # Assuming 'user_name' column exists
    print(f"Top 10 recommended products for user_id = {user_id} ({user_name})")
    print(f"Product IDs: {recommendations}")
    print()

Top 10 recommended products for user_id = 1 (Operator)
Product IDs: []

Top 10 recommended products for user_id = 7 (Dini Sipahutar)
Product IDs: [137, 151, 154, 276, 78, 95, 77, 13, 305, 50]

Top 10 recommended products for user_id = 8 (Gladys)
Product IDs: [52, 95, 260, 83, 232, 45, 246, 287, 86, 148]

Top 10 recommended products for user_id = 11 (Suandika Napitupulu)
Product IDs: [83, 275, 142, 78, 177, 77, 13, 50, 137, 232]

Top 10 recommended products for user_id = 12 (Elisa)
Product IDs: []

Top 10 recommended products for user_id = 13 (Emy Sonia Sinambela)
Product IDs: [49, 142, 145, 152, 126, 78, 177, 77, 260, 13]

Top 10 recommended products for user_id = 14 (Stefhani Kezia)
Product IDs: [49, 142, 145, 152, 126, 78, 177, 77, 260, 13]

Top 10 recommended products for user_id = 15 (Josep Phyto Napitupulu)
Product IDs: [78, 177, 13, 187, 279, 287, 52, 190, 277, 148]

Top 10 recommended products for user_id = 16 (Samuel Simanjuntak)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 17 (Yoas Sahat Marulitua Hutapea)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 18 (Boas)
Product IDs: [78, 177, 13, 187, 279, 287, 52, 190, 277, 148]

Top 10 recommended products for user_id = 19 (Jimmi)
Product IDs: [49, 142, 145, 152, 126, 78, 177, 77, 260, 13]

Top 10 recommended products for user_id = 20 (Elsie)
Product IDs: [78, 148, 177, 77, 83, 305, 50, 232, 45, 187]

Top 10 recommended products for user_id = 21 (Sally Rotua Juliana Panjaitan)
Product IDs: [78, 177, 13, 187, 279, 287, 52, 190, 277, 148]

Top 10 recommended products for user_id = 22 (Natasha)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 23 (Theofil)
Product IDs: [13, 267, 279, 52, 90, 91, 154, 247, 31, 271]

Top 10 recommended products for user_id = 24 (Akses Simamora)
Product IDs: [78, 148, 177, 77, 83, 305, 50, 232, 45, 187]

Top 10 recommended products for user_id = 26 (Charlos Purba)
Product IDs: [177, 12, 137, 212, 279, 246, 52, 90, 277, 249]

Top 10 recommended products for user_id = 27 (Yosephine)
Product IDs: [13, 12, 195, 212, 277, 249, 148, 180, 95, 77]

Top 10 recommended products for user_id = 28 (Yosephine25)
Product IDs: [13, 12, 195, 212, 277, 249, 148, 180, 95, 77]

Top 10 recommended products for user_id = 29 (Angelica Theresia Manurung)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 30 (Febri Sihotang)
Product IDs: [260, 12, 229, 212, 249, 180, 31, 78, 95, 177]

Top 10 recommended products for user_id = 32 (Ester anastasia marsada uli Simamora)
Product IDs: [78, 177, 50, 45, 212, 249, 275, 151, 77, 13]

Top 10 recommended products for user_id = 33 (Viranty Napitupulu)
Product IDs: [137, 78, 267, 102, 95, 77, 13, 305, 50, 232]

Top 10 recommended products for user_id = 34 (Silvany Putri Sipahutar)
Product IDs: [78, 305, 50, 137, 232, 187, 90, 29, 180, 54]

Top 10 recommended products for user_id = 35 (Juna)
Product IDs: [95, 260, 50, 12, 28, 49, 246, 89, 29, 31]

Top 10 recommended products for user_id = 36 (Emely Simanjuntak)
Product IDs: [20, 77, 45, 212, 246, 287, 190, 249, 151, 29]

Top 10 recommended products for user_id = 37 (Elsa Klariza Silalahi)
Product IDs: [13, 267, 279, 52, 90, 91, 154, 247, 31, 271]

Top 10 recommended products for user_id = 38 (Anita)
Product IDs: [95, 260, 83, 195, 246, 90, 277, 154, 142, 72]

Top 10 recommended products for user_id = 39 (Mesya Angeliqa Hutagalung)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 40 (Cecilia)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 41 (aqustin)
Product IDs: [83, 305, 12, 45, 49, 86, 277, 29, 31, 72]

Top 10 recommended products for user_id = 42 (siska)
Product IDs: [78, 95, 305, 137, 229, 246, 89, 275, 70, 291]

Top 10 recommended products for user_id = 43 (Mutiara Enjelina)
Product IDs: [95, 260, 137, 45, 187, 229, 49, 246, 154, 29]

Top 10 recommended products for user_id = 44 (Hansel)
Product IDs: [12, 45, 49, 86, 277, 29, 31, 72, 95, 177]

Top 10 recommended products for user_id = 45 (Hans)
Product IDs: [13, 137, 45, 187, 28, 227, 279, 275, 151, 154]

Top 10 recommended products for user_id = 46 (Sandi nainggolan)
Product IDs: [78, 95, 305, 137, 229, 246, 89, 275, 70, 291]

Top 10 recommended products for user_id = 47 (Raj Damanik)
Product IDs: [78, 148, 177, 77, 83, 305, 50, 12, 175, 232]

Top 10 recommended products for user_id = 48 (SABAR MARTUA TAMBA)
Product IDs: [12, 137, 212, 279, 246, 52, 90, 277, 249, 151]

Top 10 recommended products for user_id = 49 (Horas Siregar)
Product IDs: [78, 77, 83, 13, 12, 187, 229, 287, 89, 90]

Top 10 recommended products for user_id = 51 (Putri Napitupulu)
Product IDs: []

Top 10 recommended products for user_id = 52 (dedi)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 53 (jacob)
Product IDs: []

Top 10 recommended products for user_id = 54 (Merry Tamba)
Product IDs: [137, 34, 151, 154, 78, 95, 77, 13, 305, 50]

Top 10 recommended products for user_id = 55 (rosa)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 56 (Yoseplin)
Product IDs: [95, 227, 70, 177, 77, 260, 83, 50, 12, 137]

Top 10 recommended products for user_id = 57 (Anita Munthe)
Product IDs: [78, 95, 305, 137, 229, 246, 89, 275, 70, 291]

Top 10 recommended products for user_id = 58 (Sulastri)
Product IDs: [78, 95, 305, 137, 229, 246, 89, 275, 70, 291]

Top 10 recommended products for user_id = 59 (Yosevyn Reginae Sipahutar)
Product IDs: [12, 78, 28, 227, 91, 102, 247, 70, 268, 95]

Top 10 recommended products for user_id = 60 (Putri Ayu Manurung)
Product IDs: [95, 83, 13, 28, 212, 246, 249, 220, 106, 128]

Top 10 recommended products for user_id = 61 (Reinaldy Hutapea)
Product IDs: [78, 260, 137, 232, 267, 195, 180, 177, 77, 83]

Top 10 recommended products for user_id = 62 (Missyolin Eunike Rungguni)
Product IDs: [78, 177, 13, 187, 279, 287, 52, 190, 277, 148]

Top 10 recommended products for user_id = 63 (Arga)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 64 (Maria)
Product IDs: [95, 77, 50, 229, 227, 279, 52, 86, 277, 275]

Top 10 recommended products for user_id = 65 (Sarah Tobing)
Product IDs: [95, 260, 137, 45, 187, 49, 246, 154, 29, 142]

Top 10 recommended products for user_id = 66 (OLOAN BONAR NAINGGOLAN)
Product IDs: [13, 78, 28, 195, 178, 190, 35, 207, 95, 177]

Top 10 recommended products for user_id = 67 (Wilona)
Product IDs: [77, 45, 212, 246, 287, 190, 249, 151, 29, 291]

Top 10 recommended products for user_id = 88 (jaskia)
Product IDs: []

Top 10 recommended products for user_id = 89 (Necia Gloria Amanda Sitohang)
Product IDs: [137, 212, 151, 154, 78, 95, 77, 13, 305, 50]

Top 10 recommended products for user_id = 90 (Cheryl Naomi Siagian)
Product IDs: [21, 77, 13, 305, 137, 267, 49, 90, 253, 250]

Top 10 recommended products for user_id = 91 (Hasan Sinaga)
Product IDs: [78, 177, 13, 187, 287, 52, 190, 277, 148, 29]

Top 10 recommended products for user_id = 92 (Putri Tamara Gultom)
Product IDs: [137, 151, 154, 95, 77, 13, 305, 50, 12, 28]

Top 10 recommended products for user_id = 93 (Cindy)
Product IDs: [77, 13, 187, 195, 227, 212, 190, 89, 249, 102]

Top 10 recommended products for user_id = 94 (CHRISTIN ELISABETH THERESYA SIREGAR)
Product IDs: [78, 95, 305, 137, 229, 246, 89, 275, 70, 291]

Top 10 recommended products for user_id = 95 (Tesya Nopiana Siahaan)
Product IDs: [260, 13, 305, 12, 137, 279, 246, 275, 148, 151]

Top 10 recommended products for user_id = 96 (Rentha Pangaribuan)
Product IDs: [49, 142, 145, 152, 126, 78, 177, 77, 260, 13]

Top 10 recommended products for user_id = 97 (Maria Laura Nasution)
Product IDs: [12, 78, 227, 91, 102, 247, 70, 268, 95, 177]

Top 10 recommended products for user_id = 98 (Andreas Arta Putra Manik)
Product IDs: [49, 142, 145, 152, 126, 78, 177, 77, 260, 13]

Top 10 recommended products for user_id = 99 (Julianti Sitorus)
Product IDs: [305, 267, 195, 229, 287, 52, 86, 277, 275, 29]

Top 10 recommended products for user_id = 100 (Onra Imanuel)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 101 (Angelica Manurung)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 102 (Trinita Situmorang)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 103 (Tasya simanjungak)
Product IDs: []

Top 10 recommended products for user_id = 104 (Rico Situmorang)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 105 (tasya diva aulia s)
Product IDs: [78, 95, 12, 187, 49, 246, 89, 91, 154, 29]

Top 10 recommended products for user_id = 106 (Tabitha Aquila)
Product IDs: [95, 77, 50, 229, 227, 279, 52, 86, 277, 275]

Top 10 recommended products for user_id = 107 (Dian)
Product IDs: [260, 95, 83, 13, 305, 229, 190, 90, 220, 106]

Top 10 recommended products for user_id = 108 (Christian Jhon Pranata Panjaitan)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 109 (johanna)
Product IDs: [260, 13, 305, 12, 137, 279, 246, 275, 148, 151]

Top 10 recommended products for user_id = 110 (Marcelino Manalu)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 111 (Fritz Marpaung)
Product IDs: [137, 190, 151, 154, 78, 95, 77, 13, 305, 50]

Top 10 recommended products for user_id = 112 (Saimarito)
Product IDs: [78, 177, 13, 187, 279, 287, 52, 190, 277, 148]

Top 10 recommended products for user_id = 113 (Marianne Wensesla Solang)
Product IDs: [95, 260, 137, 45, 187, 229, 49, 246, 154, 29]

Top 10 recommended products for user_id = 114 (CHRISTIAN THEOFANI NAPITUPULU)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 116 (Eirene)
Product IDs: [95, 12, 187, 49, 246, 89, 91, 154, 29, 247]

Top 10 recommended products for user_id = 117 (Tria Jessica Tampubolon)
Product IDs: [78, 177, 13, 187, 279, 287, 52, 190, 277, 148]

Top 10 recommended products for user_id = 118 (Rizka)
Product IDs: [49, 142, 145, 152, 126, 78, 177, 77, 260, 13]

Top 10 recommended products for user_id = 119 (Theresia Herlita Sinaga)
Product IDs: [137, 249, 151, 154, 78, 95, 77, 13, 305, 50]

Top 10 recommended products for user_id = 120 (Grace Situmorang)
Product IDs: [83, 28, 267, 195, 287, 89, 142, 70, 291, 78]

Top 10 recommended products for user_id = 121 (Jensri)
Product IDs: [137, 151, 154, 134, 78, 95, 77, 13, 305, 50]

Top 10 recommended products for user_id = 122 (Van Christ John Hutajulu)
Product IDs: [78, 177, 13, 187, 279, 287, 52, 190, 277, 148]

Top 10 recommended products for user_id = 123 (Diva)
Product IDs: [13, 28, 267, 279, 90, 277, 142, 80, 271, 78]

Top 10 recommended products for user_id = 124 (Lovinta)
Product IDs: [305, 12, 45, 49, 86, 277, 29, 31, 72, 95]

Top 10 recommended products for user_id = 125 (Maryono)
Product IDs: [95, 260, 13, 229, 190, 89, 80, 78, 177, 77]

Top 10 recommended products for user_id = 127 (Debora)
Product IDs: [49, 142, 145, 152, 126, 78, 177, 77, 260, 13]

Top 10 recommended products for user_id = 128 (lawy xenna)
Product IDs: [12, 78, 227, 91, 102, 247, 70, 268, 95, 177]

Top 10 recommended products for user_id = 129 (Carol)
Product IDs: [95, 12, 187, 49, 246, 89, 91, 154, 29, 247]

Top 10 recommended products for user_id = 130 (Luana)
Product IDs: [78, 95, 305, 137, 229, 246, 89, 275, 70, 291]

Top 10 recommended products for user_id = 132 (sisil)
Product IDs: [78, 177, 13, 187, 279, 287, 52, 190, 277, 148]

Top 10 recommended products for user_id = 133 (Raja Hizkia D. simangunsong)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 134 (Wahyu Hasibuan)
Product IDs: [78, 25, 83, 12, 246, 142, 152, 126, 77, 13]

Top 10 recommended products for user_id = 135 (Faiza)
Product IDs: [95, 12, 267, 52, 86, 89, 277, 253, 250, 19]

Top 10 recommended products for user_id = 136 (Yulanda)
Product IDs: [49, 142, 145, 152, 126, 78, 177, 77, 260, 13]

Top 10 recommended products for user_id = 137 (Gavin)
Product IDs: [78, 95, 305, 137, 229, 246, 89, 275, 70, 291]

Top 10 recommended products for user_id = 138 (Ezra)
Product IDs: [78, 95, 305, 137, 214, 229, 246, 89, 275, 154]

Top 10 recommended products for user_id = 139 (Otniel Simanungkalit)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 140 (Amanda Artha Regina Simbolon)
Product IDs: [13, 12, 195, 212, 277, 249, 148, 180, 95, 77]

Top 10 recommended products for user_id = 141 (Christian Ben)
Product IDs: [78, 177, 13, 187, 279, 287, 52, 190, 277, 148]

Top 10 recommended products for user_id = 142 (kenan)
Product IDs: [50, 232, 187, 52, 19, 154, 180, 183, 145, 177]

Top 10 recommended products for user_id = 143 (Roy)
Product IDs: [95, 195, 78, 49, 287, 277, 275, 224, 180, 80]

Top 10 recommended products for user_id = 144 (Krisna)
Product IDs: [78, 177, 13, 187, 279, 287, 52, 277, 148, 29]

Top 10 recommended products for user_id = 145 (Jeremia sinaga)
Product IDs: [78, 83, 12, 246, 142, 152, 126, 77, 13, 50]

Top 10 recommended products for user_id = 146 (Natanael Simanullang)
Product IDs: []

Top 10 recommended products for user_id = 149 (Ria Anjelina Sihotang)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 150 (Rofi)
Product IDs: []

Top 10 recommended products for user_id = 151 (Natanael)
Product IDs: [12, 13, 229, 145, 77, 260, 50, 137, 187, 28]

Top 10 recommended products for user_id = 152 (Exaudi)
Product IDs: [12, 78, 227, 91, 102, 247, 70, 268, 95, 177]

Top 10 recommended products for user_id = 153 (Putri Siagian)
Product IDs: [49, 142, 145, 152, 126, 78, 177, 77, 260, 13]

Top 10 recommended products for user_id = 154 (Tio Manalu)
Product IDs: [12, 78, 227, 91, 102, 247, 70, 268, 95, 177]

Top 10 recommended products for user_id = 155 (Eladita Nadeak)
Product IDs: [61, 260, 13, 137, 267, 49, 52, 17, 31, 291]

Top 10 recommended products for user_id = 156 (ade tresia sianturi)
Product IDs: [260, 12, 229, 212, 249, 180, 31, 78, 95, 177]

Top 10 recommended products for user_id = 157 (Angelika)
Product IDs: [305, 12, 45, 49, 86, 277, 29, 31, 72, 95]

Top 10 recommended products for user_id = 158 (Ridho)
Product IDs: [49, 142, 145, 152, 126, 78, 177, 77, 260, 13]

Top 10 recommended products for user_id = 159 (Silvia)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 160 (Sry Deviani Tambunan)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 161 (Yohana Tambunan)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 162 (Beatrice Anggraini Siahaan)
Product IDs: [78, 177, 13, 187, 279, 287, 52, 190, 277, 148]

Top 10 recommended products for user_id = 163 (Sarah)
Product IDs: [78, 137, 177, 305, 28, 195, 287, 275, 151, 31]

Top 10 recommended products for user_id = 164 (Mega Marbun)
Product IDs: [78, 177, 13, 187, 279, 287, 52, 190, 277, 148]

Top 10 recommended products for user_id = 165 (Febiola Alya Hutagalung)
Product IDs: [39, 78, 177, 13, 187, 279, 287, 52, 190, 277]

Top 10 recommended products for user_id = 166 (Cici Yanti Lubis)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 167 (James Frans Rizky Tambunan)
Product IDs: [95, 260, 13, 229, 190, 89, 80, 78, 177, 77]

Top 10 recommended products for user_id = 168 (Olyvia Siahaan)
Product IDs: [95, 12, 187, 49, 246, 89, 91, 154, 29, 247]

Top 10 recommended products for user_id = 169 (Yohanna Melani Sihotang)
Product IDs: []

Top 10 recommended products for user_id = 171 (Rony Bakara)
Product IDs: [137, 151, 154, 78, 95, 177, 77, 13, 305, 50]

Top 10 recommended products for user_id = 172 (Putri)
Product IDs: [78, 95, 305, 137, 229, 246, 89, 275, 70, 291]

Top 10 recommended products for user_id = 173 (Weny)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 174 (dafne)
Product IDs: [95, 12, 187, 49, 246, 89, 91, 154, 29, 247]

Top 10 recommended products for user_id = 177 (rony)
Product IDs: [305, 137, 195, 279, 95, 77, 260, 83, 13, 50]

Top 10 recommended products for user_id = 178 (Youni Tasya Lumban Tobing)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 179 (Astri)
Product IDs: [78, 95, 305, 137, 246, 89, 275, 70, 291, 177]

Top 10 recommended products for user_id = 180 (jes)
Product IDs: [78, 148, 177, 77, 83, 305, 50, 232, 45, 187]

Top 10 recommended products for user_id = 182 (Roberto)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 191 (Agnes Elyestra)
Product IDs: [95, 260, 305, 137, 187, 195, 229, 279, 275, 19]

Top 10 recommended products for user_id = 194 (Patresia)
Product IDs: [95, 12, 187, 49, 246, 89, 91, 154, 29, 247]

Top 10 recommended products for user_id = 195 (rani)
Product IDs: [78, 95, 305, 137, 229, 246, 89, 275, 70, 291]

Top 10 recommended products for user_id = 196 (Anastasya Marpaung)
Product IDs: [12, 137, 212, 279, 246, 52, 90, 277, 249, 151]

Top 10 recommended products for user_id = 197 (bless)
Product IDs: [312, 138, 130, 195, 49, 142, 145, 152, 126, 78]

Top 10 recommended products for user_id = 198 (pita)
Product IDs: [149, 137, 151, 154, 78, 95, 77, 13, 305, 50]

Top 10 recommended products for user_id = 199 (Agustin)
Product IDs: [137, 190, 151, 154, 78, 95, 77, 13, 305, 50]

Top 10 recommended products for user_id = 200 (Yohana)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 201 (Anggi Pratiwi Nainggolan)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 207 (Christin Adelia Pratiwi Sihite)
Product IDs: [78, 95, 305, 137, 229, 246, 89, 275, 70, 291]

Top 10 recommended products for user_id = 208 (Christina)
Product IDs: [305, 12, 45, 49, 86, 277, 29, 31, 72, 95]

Top 10 recommended products for user_id = 209 (hiskia)
Product IDs: [78, 275, 148, 177, 77, 83, 305, 50, 232, 45]

Top 10 recommended products for user_id = 210 (Nessy)
Product IDs: [260, 78, 95, 177, 77, 305, 187, 267, 246, 90]

Top 10 recommended products for user_id = 211 (Osin Jentia Rosni Manullang)
Product IDs: [95, 12, 267, 52, 86, 89, 277, 253, 250, 19]

Top 10 recommended products for user_id = 212 (Bennedict Tambunan)
Product IDs: [137, 151, 154, 78, 95, 77, 13, 305, 50, 12]

Top 10 recommended products for user_id = 213 (osin manullang)
Product IDs: [95, 12, 267, 52, 86, 89, 277, 253, 250, 19]

Top 10 recommended products for user_id = 214 (Noni Jelia Feby sipayung)
Product IDs: [260, 95, 83, 13, 305, 229, 190, 90, 220, 106]

Top 10 recommended products for user_id = 215 (Liony tamara lewinsky)
Product IDs: [12, 137, 212, 279, 246, 52, 90, 277, 249, 151]

Top 10 recommended products for user_id = 216 (Feronika)
Product IDs: [95, 12, 267, 52, 86, 89, 277, 253, 250, 19]

Top 10 recommended products for user_id = 217 (Walker Valentinus Simanjuntak)
Product IDs: [78, 287, 148, 177, 77, 83, 305, 50, 232, 45]

Top 10 recommended products for user_id = 218 (Rusdeni)
Product IDs: [177, 260, 50, 137, 45, 212, 279, 49, 249, 275]

Top 10 recommended products for user_id = 219 (Elsaday)
Product IDs: [52, 95, 260, 83, 232, 45, 246, 287, 86, 148]

Top 10 recommended products for user_id = 220 (Hanny Yosephine)
Product IDs: [78, 12, 246, 142, 152, 126, 77, 83, 13, 50]

Top 10 recommended products for user_id = 223 (Yuly)
Product IDs: [137, 78, 267, 102, 95, 77, 13, 305, 50, 232]
